Q1. Conduct a chi-square goodness of fit test to determine if the distribution of colors of M&Ms in a bag 
matches the expected distribution of 20% blue, 20% orange, 20% green, 10% yellow, 10% red, and 20% 
brown. Use Python to perform the test with a significance level of 0.05

In [1]:
import scipy.stats as stat

In [2]:
import numpy as np

In [3]:
## No of hours student study dialy in weekly basis

In [4]:
# Observed data is taken randomly
observed_data = [18,22,20,10,12,18]
expected_data = [20,20,20,10,10,20]

In [5]:
sum(expected_data), sum(observed_data)

(100, 100)

In [6]:
## Chi square goodness of fit 
chisquare_test_statistics_value, p_value = stat.chisquare(observed_data, expected_data)

In [7]:
print(chisquare_test_statistics_value),print(p_value)

1.0
0.9625657732472964


(None, None)

In [8]:
## Find the critical value
significance_value = 0.05
dof= len(observed_data)-1
critical_value=stat.chi2.ppf(1-significance_value,dof)

In [9]:
print(critical_value)

11.070497693516351


In [10]:
if chisquare_test_statistics_value > critical_value:
    print("Reject the null hypothesis")
else:
    print("Accept the null hypothesis")

Accept the null hypothesis


Q2. Use Python to calculate the chi-square statistic and p-value for a contingency table with the following 
data

In [22]:
import numpy as np
from scipy.stats import chi2_contingency

# Create the contingency table
data = np.array([[20, 15],
                 [10, 25],
                 [15, 20]])

# Perform the chi-square test
chi2_stat, p_value, dof, expected = chi2_contingency(data)

# Print the results
print(f"Chi-square statistic: {chi2_stat}")
print(f"P-value: {p_value}")
print(f"Degrees of freedom: {dof}")
print("Expected frequencies:")
print(expected)


Chi-square statistic: 5.833333333333334
P-value: 0.05411376622282158
Degrees of freedom: 2
Expected frequencies:
[[15. 20.]
 [15. 20.]
 [15. 20.]]


Q3. A study of the prevalence of smoking in a population of 500 individuals found that 60 individuals 
smoked. Use Python to calculate the 95% confidence interval for the true proportion of individuals in the 
population who smoke.

In [23]:
import math

total_population = 500
sample_size = 60
sample_proportion =  1.0
Confidence_interval = 0.95
alpha = 1- Confidence_interval

In [27]:
z_critical = stat.norm.ppf(1 - alpha / 2)

In [28]:
se_sample_proportion = math.sqrt((sample_proportion * (1 - sample_proportion)) / sample_size)

In [29]:
margin_of_error = z_critical * se_sample_proportion

In [30]:
lower_limit = sample_proportion - margin_of_error
upper_limit = sample_proportion + margin_of_error

# Print the results
print(f"Sample Proportion: {sample_proportion:.4f}")
print(f"Margin of Error: {margin_of_error:.4f}")
print(f"95% Confidence Interval: [{lower_limit:.4f}, {upper_limit:.4f}]")

Sample Proportion: 1.0000
Margin of Error: 0.0000
95% Confidence Interval: [1.0000, 1.0000]


q4. Calculate the 90% confidence interval for a sample of data with a mean of 75 and a standard deviation 
of 12 using Python. Interpret the results.

In [32]:
confidence_interval = 0.90 
mean = 75
standard_deviation = 12
sample_size = 30
degree_of_freedom = 29
alpha = 0.10
t_critical = stat.t.ppf((1 + confidence_interval) / 2, degree_of_freedom)
print(t_critical)

1.6991270265334972


In [33]:
margin_of_error = t_critical * (standard_deviation / np.sqrt(sample_size))

In [35]:
lower_bound = mean - margin_of_error
upper_bound = mean + margin_of_error
print(lower_bound)
print(upper_bound)

71.27739919800369
78.72260080199631


Q5. Calculate the 95% confidence interval for a sample of data with a mean of 50 and a standard deviation 
of 5 using Python. Interpret the results.

In [37]:
confidence_interval = 0.95 
mean = 50
standard_deviation = 5
sample_size = 30
degree_of_freedom = 29
alpha = 0.05
t_critical = stat.t.ppf((1 + confidence_interval) / 2, degree_of_freedom)
print("T Score", t_critical)
margin_of_error = t_critical * (standard_deviation / np.sqrt(sample_size))
lower_bound = mean - margin_of_error
upper_bound = mean + margin_of_error
print("Lower bound value = " , lower_bound)
print("Upper bound value = " , upper_bound)

T Score 2.045229642132703
Lower bound value =  48.1329693162095
Upper bound value =  51.8670306837905


Q6. A random sample of 1000 people was asked if they preferred Coke or Pepsi. Of the sample, 520 
preferred Coke. Calculate a 99% confidence interval for the true proportion of people in the population who 
prefer Coke

In [39]:
sample_size = 1000
confidence_interval = 0.99
alpha = 0.01
# here in this we dont know the standard deviation 
# confidence_interval = p + / - * root of p(1-p)/n
# p = number of people who prefer coke / total sample size = 520/1000 = 0.52
z = 1-confidence_interval
z_critical = stat.norm.ppf(1 - alpha / 2) # this value from the z table we will get
print("z value =", z_critical)

z value = 2.5758293035489004


In [42]:
lower_bound = 0.52 - 2.5576 * np.sqrt(0.52*0.48/1000)
upper_bound = 0.52 + 2.5576 * np.sqrt(0.52*0.48/1000)
print("Lower bound value = " , lower_bound)
print("Upper bound value = " , upper_bound)

Lower bound value =  0.4795931575980503
Upper bound value =  0.5604068424019497


who prefer Coke is likely to fall within the range of 48.0% to 56.0%

Q9. A study was conducted to determine if there is an association between smoking status (smoker or 
non-smoker) and lung cancer diagnosis (yes or no). The results are shown in the contingency table below. 
Conduct a chi-square test for independence to determine if there is a significant association between 
smoking status and lung cancer diagnosis.

In [44]:
data = np.array([[60,140],
                 [30,170]])

In [45]:
data

array([[ 60, 140],
       [ 30, 170]])

In [48]:
chi2_stat, p_value, dof, expected = chi2_contingency(data)

In [49]:
print(f"Chi-square statistic: {chi2_stat}")
print(f"P-value: {p_value}")
print(f"Degrees of freedom: {dof}")
print("Expected frequencies:")
print(expected)

Chi-square statistic: 12.057347670250895
P-value: 0.0005158863863703744
Degrees of freedom: 1
Expected frequencies:
[[ 45. 155.]
 [ 45. 155.]]


p value(0.005) is less than significance value (0.05) we reject null hypothesis.